### ISSUE TITLE
SDF - 6 niveaux de navigation visibles dans le menu WP

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#120]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: Sous menu dans le désordre
[Open #108 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/108)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-31/b7c38c28-2f7b-4919-baa3-88ee46a4270c.png'>![SDF - Sous menu dans le désordre](https://usersnappublic.s3.amazonaws.com/2017-07-19/17-31/aef27cb8-ca5f-4481-b583-a30854262b8a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-31/b7c38c28-2f7b-4919-baa3-88ee46a4270c.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://events.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/events/fr/index-fr-html/page-89415-fr-html/magistrale/page-124414-fr-html/page-124418-fr-html/](http://10.92.104.248:18081/toto?url1=http://events.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/events/fr/index-fr-html/page-89415-fr-html/magistrale/page-124414-fr-html/page-124418-fr-html/)
**Screen size**: 2049 x 1152 **Browser size**: 2049 x 953

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Les entrées de menu indiquées sur le snapshot n'existent pas sur le site original (events.epfl.ch) donc est-ce qu'il y a eu un changement sur le site Jahia et que ça a disparu? si ce n'est pas le cas d'où est-ce que ça peut venir ?

**Comment by Escapevelocitycham** [comment]
A nouveau un titre qui ne correspond pas au problème. Etait : Sous menu dans le désordre.
Changé par HD

Dans ce cas, il y a jusqu'à 6 niveaux de navigation : Home / Grandes manifestations / Magistrales / Archives / Magistrales 201x / Programme 201x
Dans le menu horizontal, Jahia affiche les niveaux 2 puis 3 et 4 (drop down) mais pas le 5 et suivants. 
WP affiche le niveau 2 dans la barre puis tous les niveaux en drop down. Par contre les niveaux 4, 5 et 6 sont confondus, il n'y a pas/plus de hiérarchisation (menu en gras pour n3 et en "normal" pour n4 dans Jahia)

**Comment by Escapevelocitycham** [comment]
@alinekeller Je t'assigne cette issue avec un peu le même doute qu'hier (toi ou DevTeam?)
Mon commentaire précédent explique la situation.
Je pense que la question est :
a) Faut-il styliser les niveaux de navigation (indenter par exemple) ou
b) Faut-il faire comme Jahia et ne pas montrer tous les niveaux dans le menu, mais dans ce cas ... comment montrer les pages de bas niveaux ?
A nouveau n'hésites pas à me ré-assigner l'issue le cas échéant.

**Comment by alinekeller** [comment]
Je propose la solution suivante:
<img width="406" alt="capture d ecran 2017-11-07 a 17 29 02" src="https://user-images.githubusercontent.com/6631947/32504942-4a17e20a-c3e1-11e7-9df9-27284f59f97e.png">

L'indentation se fait automatiquement pour chaque sous-niveau, donc qu'ils en mettent 4, 5 ou 18 ça fonctionnera pareil. Après c'est une question de bon sens d'éviter d'en mettre trop.

**Comment by alinekeller** [comment]
Du coup ça réglerait aussi cette issue: https://github.com/epfl-idevelop/jahiap/issues/186

Les niveaux sont bien séparés visuellement, je trouve la hiérarchie plus claire qu'avec ce gros espace en-dessous.

**Comment by LuluTchab** [comment]
Déployé sur http://test-web-wordpress.epfl.ch/v1-testwp/events

**Comment by Escapevelocitycham** [comment]
Elégant ... et OK pour moi
