### ISSUE TITLE
SDF - Il manque la barre de navigation

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#122]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: Il manque la barre de navigation
[Open #104 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/104)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-08/7aed79dc-499c-498b-a511-c5fa43c66eaa.png'>![SDF - Il manque la barre de navigation](https://usersnappublic.s3.amazonaws.com/2017-07-19/17-08/9c42bdf5-70c6-4f00-8df0-97e4d5cce0a0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-08/7aed79dc-499c-498b-a511-c5fa43c66eaa.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://culture.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/cultures/fr/](http://10.92.104.248:18081/toto?url1=http://culture.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/cultures/fr/)
**Screen size**: 2277 x 1280 **Browser size**: 2049 x 953

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Le contenu du site n'a pas été importé, probablement parce qu'on est arrivé au "timeout" lorsque l'on attend qu'Apache soit UP pour pouvoir importer le contenu. L'atteinte de ce timeout dépend aussi fortement de la charge de la machine et de l'état dans lequel docker se trouve.

La durée du timeout a été augmentée donc ce problème ne devrait plus apparaître, peu importe le site.
Fermeture car le timeout a été augmenté.
