### ISSUE TITLE
SDF - Ie manque le choix de la langue

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#123]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: Ie manque le choix de la langue
[Open #103 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/103)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-06/5b179331-0565-4ac2-96d4-dd25ea5b0f55.png'>![SDF - Ie manque le choix de la langue](https://usersnappublic.s3.amazonaws.com/2017-07-19/17-06/a2807c2b-a060-47b4-9b5d-40f9f5208e1e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/17-06/5b179331-0565-4ac2-96d4-dd25ea5b0f55.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://culture.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/cultures/fr/](http://10.92.104.248:18081/toto?url1=http://culture.epfl.ch&amp;url2=http://test-web-wordpress.epfl.ch/v1-testwp/cultures/fr/)
**Screen size**: 2277 x 1280 **Browser size**: 2049 x 953

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Doublon avec https://github.com/epfl-idevelop/jahiap/issues/122
Timeout lors de l'importation.
