### ISSUE TITLE
SDF - Changement de langue, connexion non sécurisée (see comments in UserSnap)

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#125]
**Sender**: sdfepfl+gabeff@gmail.com
**Comment**: Changement de langue, connexion non sécurisée (see comments in UserSnap)
[Open #101 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/101)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/15-46/500cc322-7044-4191-ba37-294e17e5ab2c.png'>![SDF - Changement de langue, connexion non sécurisée (see comments in UserSnap)](https://usersnappublic.s3.amazonaws.com/2017-07-19/15-46/bca4e3d4-76c1-453d-a737-108e6211b7a2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/15-46/500cc322-7044-4191-ba37-294e17e5ab2c.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://ccc.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lcr.html](http://10.92.104.248:18081/toto?url1=http://ccc.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lcr.html)
**Screen size**: 2049 x 1152 **Browser size**: 2049 x 989

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Pas possible de reproduire le truc. Donc on ferme.
