### ISSUE TITLE
SDF - Bandeau du haut ne déroule pas correctement (see comments in usersnap)

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#126]
**Sender**: sdfepfl+gabeff@gmail.com
**Comment**: Bandeau du haut ne déroule pas correctement
[Open #100 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/100)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/15-23/91a152de-af71-4d2d-99ad-04df8b7dab48.png'>![SDF - Bandeau du haut ne déroule pas correctement (see comments in usersnap)](https://usersnappublic.s3.amazonaws.com/2017-07-19/15-23/cf1c2f79-ae3f-4962-bb3f-4d2018c14d4c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-19/15-23/91a152de-af71-4d2d-99ad-04df8b7dab48.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://gr-co.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/gr-co.html](http://10.92.104.248:18081/toto?url1=http://gr-co.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/gr-co.html)
**Screen size**: 2049 x 1152 **Browser size**: 2049 x 989

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
En fait, lors d'un clic sur un des éléments du bandeau, au lieu d'afficher les infos par-dessus la page courante, on est redirigé sur www.epfl.ch 
Ceci provient du fait qu'il manque une référence à 2 fichiers JavaScript dans le <head> de la page. 
En ajoutant le code suivant juste avant `</head>`, ça passe :

```
<script type="text/javascript" src="//www.epfl.ch/js/jquery-epfl.min.js"></script>
   <script type="text/javascript">jQuery.noConflict();</script> 
   <script type="text/javascript" src="//www.epfl.ch/js/globalnav.js"></script>
```

**Comment by LuluTchab** [comment]
Déployé sur : http://test-web-wordpress.epfl.ch/v1-testwp/gr-co

**Comment by Escapevelocitycham** [comment]
@LuluTchab 
Bandeau se déroule correctement mais nom des facultés en noir et bandeau en F alors que site en E
D'accord avec toi la description du problème n'est pas limpide ...

**Comment by LuluTchab** [comment]
Problème mis de côté en attendant que le problème d'inclusion du header dans la bonne langue soit traité.
(https://github.com/epfl-idevelop/jahiap/issues/279#event-1329367278)

**Comment by LuluTchab** [comment]
Déployé sur http://test-web-wordpress.epfl.ch/v1-testwp/gr-co

**Comment by Escapevelocitycham** [comment]
OK pour moi
