### ISSUE TITLE
SDF - La box vidéo affiche un message d'erreur

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#131]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: La box vidéo affiche un message d'erreur
[Open #119 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/119)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-20/10-35/ea4ba377-1e61-4fac-9bb4-f32b51b42f0e.png'>![SDF - La box vidéo affiche un message d'erreur](https://usersnappublic.s3.amazonaws.com/2017-07-20/10-35/9fa50937-d98c-48f6-9685-4673e7c0ac3f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-20/10-35/ea4ba377-1e61-4fac-9bb4-f32b51b42f0e.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://test-web-wordpress.epfl.ch/v1-testwp/developpementdurable/fr/index-fr-html/mobilite/velo/publibike-lausanne/](http://test-web-wordpress.epfl.ch/v1-testwp/developpementdurable/fr/index-fr-html/mobilite/velo/publibike-lausanne/)
**Screen size**: 2049 x 1152 **Browser size**: 1708 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Sur le site original Jahia, la vidéo n'apparait pas non plus... https://developpement-durable.epfl.ch/publibike-lausanne
