### ISSUE TITLE
SDF - A certain niveau de zoom scroller vers le bas fait trembler la page

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#135]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: A certain niveau de zoom scroller vers le bas fait trembler la page
[Open #114 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/114)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-20/09-11/e5cf579c-8eb5-40be-aaec-9e45178ada58.png'>![SDF - A certain niveau de zoom scroller vers le bas fait trembler la page](https://usersnappublic.s3.amazonaws.com/2017-07-20/09-11/9bf34ab6-5e98-4919-8aef-02dea9dedf34.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-20/09-11/e5cf579c-8eb5-40be-aaec-9e45178ada58.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://test-web-wordpress.epfl.ch/v1-testwp/cdm/en/index-html/itpp/itppeducation/](http://test-web-wordpress.epfl.ch/v1-testwp/cdm/en/index-html/itpp/itppeducation/)
**Screen size**: 1708 x 960 **Browser size**: 1708 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Pas de notre ressort donc tchô bonne.
