### ISSUE TITLE
Certains éléments pas transférés

### ISSUE THREAD

**Issue by khadmal** [epfl-idevelop/jahiap#161]
INC0151924 : page teaching du site lte
4. Page Teaching
     - La liste est très incomplète

**Comment by LuluTchab** [comment]
Probablement pas à jour avec les modifications faites sur Jahia depuis import dans WordPress

**Comment by LuluTchab** [comment]
Une version statique des sites Jahia sera mise en ligne en même temps que la prochaine génération des sites WP
