### ISSUE TITLE
SDF - Site vide et message d'erreur "NOTHING FOUND", boîtes de droites apparentes

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#163]
**Sender**: sdfepfl_boscardi@gmail.com
**Comment**: Rien ne s'affiche: "NOTHING FOUND"
[Open #130 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/130)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/14-11/37aac713-456f-4dc3-b206-a169221ace41.png'>![SDF - Site vide et message d'erreur "NOTHING FOUND", boîtes de droites apparentes](https://usersnappublic.s3.amazonaws.com/2017-07-25/14-11/3c69cb82-347b-4709-89f7-2f36fe62c941.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/14-11/37aac713-456f-4dc3-b206-a169221ace41.png'>Download original image</a>

**Browser**: Firefox 54 (Mac OS X Yosemite)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://lch.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/lch](http://10.92.104.248:18081/toto?url1=http://lch.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/lch)
**Screen size**: 2160 x 1350 **Browser size**: 2160 x 1095

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Probablement que le serveur Apache n'avait pas encore démarré (timeout) lorsque le script a voulu commencer l'importation du contenu du site.
Fermeture de cette issue car le timeout a été augmenté pour le démarrage d'Apache
