### ISSUE TITLE
SDF - Espacement excessif du contenu dans le corps de page.

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#166]
**Sender**: sdfepfl+louis.munier@gmail.com
**Comment**: Espacement excessif du contenu dans le corps de page.
[Open #479 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/479)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-31/10-52/8bbef831-4715-4bab-bef9-3e374c54d033.png'>![SDF - Espacement excessif du contenu dans le corps de page.](https://usersnappublic.s3.amazonaws.com/2017-07-31/10-52/6810bcce-1697-4876-bae6-c768dd582710.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-31/10-52/8bbef831-4715-4bab-bef9-3e374c54d033.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.219:8081/compare?url=http://lsci.epfl.ch&amp;url=http://dev-web-wordpress.epfl.ch/v1-testwp/lsci](http://10.92.104.219:8081/compare?url=http://lsci.epfl.ch&amp;url=http://dev-web-wordpress.epfl.ch/v1-testwp/lsci)
**Screen size**: 2144 x 1206 **Browser size**: 2144 x 1128

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Le lien "referer" n'est pas valable (erreur renvoyée).
Comparaison faite à la main, le problème n'existe pas. Il se peut que l'outil de comparaison ajoute lui-même cette erreur. Ou alors ça vient encore d'ailleurs. Bref, pas possible à reproduire donc on ferme.
