### ISSUE TITLE
SDF - Dans une des langue, la page affiché n'est pas la bonne

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#168]
**Sender**: sdfepfl+bortolon@gmail.com
**Comment**: Change de page quand on change la langue
[Open #467 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/467)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-27/17-27/f375193e-114d-4b2e-84e8-c9fd82f848cd.png'>![SDF - Dans une des langue, la page affiché n'est pas la bonne](https://usersnappublic.s3.amazonaws.com/2017-07-27/17-27/2d4a0be7-a4b5-4468-a341-4c6399fdd712.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-27/17-27/f375193e-114d-4b2e-84e8-c9fd82f848cd.png'>Download original image</a>

**Browser**: Firefox 54 (macOS Sierra)
**Referer**: [http://10.92.104.219:8081/compare?url=http://complexdesign.epfl.ch&amp;url=http://dev-web-wordpress.epfl.ch/v1-testwp/complexdesign](http://10.92.104.219:8081/compare?url=http://complexdesign.epfl.ch&amp;url=http://dev-web-wordpress.epfl.ch/v1-testwp/complexdesign)
**Screen size**: 2560 x 1600 **Browser size**: 1920 x 1082

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Erreur sur la page pointée par le "referer"
Comparaison à la main et pas retrouvé l'erreur. Il y a effectivement des erreurs mais au niveau du menu en français, pas au niveau de ce qui est décris dans l'issue. Donc, fermeture
