### ISSUE TITLE
SDF - Lien sous wordpress renvoie à la page originale sous jahia.  Après avoir c[...]

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#178]
**Sender**: sdfepfl+louis.munier@gmail.com
**Comment**: Lien sous wordpress renvoie à la page originale sous jahia.

Après avoir cliqué sur un lien "is-academia" de la page du DAF, on se retrouve sous jahia.
[Open #426 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/426)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-27/12-42/05b87b08-c497-4164-b2f3-59e7cde67ec5.png'>![SDF - Lien sous wordpress renvoie à la page originale sous jahia.  Après avoir c(...)](https://usersnappublic.s3.amazonaws.com/2017-07-27/12-42/544dca43-9b0a-4822-922a-d17ca8f55693.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-27/12-42/05b87b08-c497-4164-b2f3-59e7cde67ec5.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://formation.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/formation](http://10.92.104.248:18081/toto?url1=http://formation.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/formation)
**Screen size**: 2144 x 1206 **Browser size**: 2144 x 1128

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Pas de gestion des liens externes, même s'ils pointent sur un site qui est migré de Jahia à WordPress. Cette gestion serait faite "automatiquement" via un proxy qui redirigera les anciennes adresses Jahia vers les nouvelles sur WordPress.
