### ISSUE TITLE
SDF - Mauvaise mise en page des sous onglets. Séparation régulière au li[...]

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#186]
**Sender**: sdfepfl+emmanuel.barriol@gmail.com
**Comment**: Problème de mise en page dans les sous onglets. Séparation régulière au lieu d'avoir un regroupement par paire
[Open #345 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/345)
**Notes**:
 - (1) Ces paires doivent être collées, et séparées par une ligne vide les unes des autres.

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/17-15/2b959d3f-789a-48d1-a70b-87209ac82a13.png'>![SDF - Mauvaise mise en page des sous onglets. Séparation régulière au li(...)](https://usersnappublic.s3.amazonaws.com/2017-07-26/17-15/fe71c00e-e1e2-437a-94c9-95dac8e756a4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/17-15/2b959d3f-789a-48d1-a70b-87209ac82a13.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://opt.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/opt](http://10.92.104.248:18081/toto?url1=http://opt.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/opt)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 917

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Est-ce que c'est un truc custom qui a été fait dans le site "opt.epfl.ch" (au niveau du CSS?) pour pouvoir ajouter un espace à cet endroit-là? 
Ou est-ce que c'est le thème qui ne gère par correctement ce genre de regroupement ?

**Comment by Escapevelocitycham** [comment]
Les éléments en gras représentent les 2ème niveau de navigation (le premier étant la barre horizontale), les éléments représentent le 3ème niveau. 
La CSS Jahia gère un espace entre les pages de 2ème niveau (yc les pages de 3ème) ... WP ne le fait pas

Il n'y a pas de CSS custom

**Comment by LuluTchab** [comment]
Déployé sur http://test-web-wordpress.epfl.ch/v1-testwp/opt
