### ISSUE TITLE
SDF - mauvais affichage SBB|CFF|FFS et la date/heure affichée est ancienne

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#200]
**Sender**: sdfepfl+kossairi@epfl.ch
**Comment**: mauvais affichage SBB|CFF|FFS et la date/heure affichée est ancienne 
[Open #283 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/283)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/12-04/0de42ede-a0c8-480e-ba4e-65d925a30d32.png'>![SDF - mauvais affichage SBB|CFF|FFS et la date/heure affichée est ancienne](https://usersnappublic.s3.amazonaws.com/2017-07-26/12-04/b0e61d6b-1cc1-453b-a6d2-e05c0c20377a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/12-04/0de42ede-a0c8-480e-ba4e-65d925a30d32.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 7)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://lpmat.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/lpmat](http://10.92.104.248:18081/toto?url1=http://lpmat.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/lpmat)
**Screen size**: 2049 x 1152 **Browser size**: 2049 x 989

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Après test en direct sur la page WordPress, ça passe. C'est bien la date actuelle qui est prise et affichée.
Le problème est peut-être un effet de bord de l'utilisation du comparateur et du proxy.

Donc, fermeture.
