### ISSUE TITLE
SDF - Map n'apparaissent pas en jahia mais apparaissent en wordpress avec bout d[...]

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#207]
**Sender**: sdfepfl+youssef.saied@gmail.com
**Comment**: Map n'apparaissent pas en jahia mais apparaissent en wordpress avec bout de code.
[Open #147 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/147)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/15-18/eb76e6bb-d542-40cf-b943-11df33941c43.png'>![SDF - Map n'apparaissent pas en jahia mais apparaissent en wordpress avec bout d(...)](https://usersnappublic.s3.amazonaws.com/2017-07-25/15-18/d0576cc2-d1e7-48e0-a46d-ffdc0d3e80cb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/15-18/eb76e6bb-d542-40cf-b943-11df33941c43.png'>Download original image</a>

**Browser**: Firefox 54 (Ubuntu)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://courtine-lab.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/courtine-lab](http://10.92.104.248:18081/toto?url1=http://courtine-lab.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/courtine-lab)
**Screen size**: 2049 x 1152 **Browser size**: 2049 x 1010

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Aucune trace de l'iframe contenant la carte Google dans le site Jahia. Celui-ci a dû changer depuis que l'export du ZIP a été fait.

**Comment by LuluTchab** [comment]
On peut donc fermer
