### ISSUE TITLE
SDF - Dans le choix de langue, English est clicable alors que la page est en anglais

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#213]
**Sender**: sdfepfl+marwan.elchazli@epfl.ch
**Comment**: lien en plus mais inutile dans wordpress
[Open #232 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/232)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/08-40/24e4b51f-0211-402d-897e-9a7bbf9c4d89.png'>![SDF - Dans le choix de langue, English est clicable alors que la page est en anglais](https://usersnappublic.s3.amazonaws.com/2017-07-26/08-40/eb64424e-94f1-4609-a9cc-d0b22a496082.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-26/08-40/24e4b51f-0211-402d-897e-9a7bbf9c4d89.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 8.1)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://aphys.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/aphys](http://10.92.104.248:18081/toto?url1=http://aphys.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/aphys)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 659

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
C'est le comportement par défaut du plugin Polylang. Même dans la langue courante, le lien est actif. Donc fermeture
