### ISSUE TITLE
SDF - apparence du menu des onglet a été remplacé une par apparence standard

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#215]
**Sender**: sdfepfl+elhazzaz@epfl.ch
**Comment**: format different du menu (plus large)
[Open #196 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/196)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/19-29/26da621f-0948-4f7e-b24f-0a6fa148287c.png'>![SDF - apparence du menu des onglet a été remplacé une par apparence standard](https://usersnappublic.s3.amazonaws.com/2017-07-25/19-29/4c342f21-fe27-48e1-b70d-6075f608f541.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/19-29/26da621f-0948-4f7e-b24f-0a6fa148287c.png'>Download original image</a>

**Browser**: Firefox 52 (Windows 7)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://cdmit.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/cdmit](http://10.92.104.248:18081/toto?url1=http://cdmit.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/cdmit)
**Screen size**: 2400 x 1500 **Browser size**: 2400 x 1361

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
A priori c'est une modification custom faite du côté de Jahia donc pas supportée. On ferme
