### ISSUE TITLE
SDF - Le trait qui souligne un lien se prolonge en dessous des images qui le précèdent

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#223]
**Sender**: sdfepfl+emmanuel.barriol@gmail.com
**Comment**: Le trait qui souligne un lien se prolonge en dessous des images qui le précèdent
[Open #173 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/173)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/17-29/6764fd51-38e6-4319-90f3-ae79ec4d7b1e.png'>![SDF - Le trait qui souligne un lien se prolonge en dessous des images qui le précèdent](https://usersnappublic.s3.amazonaws.com/2017-07-25/17-29/5cccf7b2-053d-4fd3-ad40-268968a93f0f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-25/17-29/6764fd51-38e6-4319-90f3-ae79ec4d7b1e.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://macline.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/macline](http://10.92.104.248:18081/toto?url1=http://macline.epfl.ch&amp;url2=http://dev-web-wordpress.epfl.ch/v1-testwp/macline)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 917

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Problème non trouvé sur le site WordPress. Peut-être qu'il s'agit du proxy qui change trop de choses.

**Comment by LuluTchab** [comment]
Du coup, on peut fermer...
