### ISSUE TITLE
SDF - une partie du corps du texte n'a pas été inclus dans le tableau

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#233]
**Sender**: sdfepfl+pablo.mercadodelrio@epfl.ch
**Comment**: une partie du corps du texte n'a pas été inclus dans le tableau
[Open #739 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/739)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/11-07/8af9246d-75de-42bc-a940-ce4149ecd5d1.png'>![SDF - une partie du corps du texte n'a pas été inclus dans le tableau](https://usersnappublic.s3.amazonaws.com/2017-08-11/11-07/8fca7dc5-058f-41d4-ab75-8d1f9fe32eb0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/11-07/8af9246d-75de-42bc-a940-ce4149ecd5d1.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [http://10.92.104.219:8081/compare?user_id=50&amp;url1=http://3dcamp.epfl.ch/&amp;url2=http://qa1-web-wordpress.epfl.ch/v1-testwp/3dcamp](http://10.92.104.219:8081/compare?user_id=50&amp;url1=http://3dcamp.epfl.ch/&amp;url2=http://qa1-web-wordpress.epfl.ch/v1-testwp/3dcamp)
**Screen size**: 1920 x 1080 **Browser size**: 1922 x 952

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Après contrôle sur site WordPress, le problème n'est pas présent. ça doit provenir de la remise en forme faite par le proxy. Du coup, fermeture.
