### ISSUE TITLE
SDF - Commentaire visible sur la page WP (pas sur Jahia)

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#238]
**Sender**: sdfepfl+sijing.huang@gmail.com
**Comment**: Commentaire visible sur la page WP (pas sur Jahia)
[Open #744 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/744)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/11-50/db0b720d-129c-4f05-8c8b-b8fde87e2ead.png'>![SDF - Commentaire visible sur la page WP (pas sur Jahia)](https://usersnappublic.s3.amazonaws.com/2017-08-11/11-50/bb9a0d11-2380-4e38-a70c-92482f93a59b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/11-50/db0b720d-129c-4f05-8c8b-b8fde87e2ead.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [http://10.92.104.219:8081/compare?user_id=48&amp;url1=http://help-actu.epfl.ch&amp;url2=http://qa2-web-wordpress.epfl.ch/v1-testwp/outilactuhelp](http://10.92.104.219:8081/compare?user_id=48&amp;url1=http://help-actu.epfl.ch&amp;url2=http://qa2-web-wordpress.epfl.ch/v1-testwp/outilactuhelp)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 813

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Pas visible dans le site Jahia initial donc les données ont probablement changé.
