### ISSUE TITLE
SDF - Mise en page différente (tableau / paragraphe)

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#243]
**Sender**: sdfepfl+sijing.huang@gmail.com
**Comment**: Mise en page différente (tableau / paragraphe)
[Open #749 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/749)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/13-54/eba092d2-30f5-460e-94d2-52db04430aee.png'>![SDF - Mise en page différente (tableau / paragraphe)](https://usersnappublic.s3.amazonaws.com/2017-08-11/13-54/b050d8a1-fd13-4038-acc4-062700032c1e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-11/13-54/eba092d2-30f5-460e-94d2-52db04430aee.png'>Download original image</a>

**Browser**: Chrome 60 (Windows 10)
**Referer**: [http://10.92.104.219:8081/compare?user_id=48&amp;url1=http://innoseed-enac.epfl.ch&amp;url2=http://qa1-web-wordpress.epfl.ch/v1-testwp/enac-innoseed](http://10.92.104.219:8081/compare?user_id=48&amp;url1=http://innoseed-enac.epfl.ch&amp;url2=http://qa1-web-wordpress.epfl.ch/v1-testwp/enac-innoseed)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 813

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Le contenu semble avoir changé du côté de Jahia donc fermeture
