### ISSUE TITLE
SDF - Il y a des onglets disponible en plus sur la version WP anglaise du site

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#252]
**Comment**: 193	Il y a des onglets disponible en plus sur la version WP anglaise du site
[Open #809 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test4wwp-by-sdf-6878f3ee/809)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-22/15-44/06bae95c-0715-456a-ac52-00e26e4ae2da.png'>![SDF - Il y a des onglets disponible en plus sur la version WP anglaise du site](https://usersnappublic.s3.amazonaws.com/2017-08-22/15-44/04c49d6a-4e3a-452d-8032-5127d270fbe0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-22/15-44/06bae95c-0715-456a-ac52-00e26e4ae2da.png'>Download original image</a>

**Browser**: Firefox 55 (Windows 10)
**Referer**: [https://lh5.googleusercontent.com/fhIefT3XeJNU_3-gPWrNHJneLg6KrYCqF9Ps0uQecwwAUHHk3b62B0kvxo3z4o4c8arDTzodz6SxbYU=w1366-h635](https://lh5.googleusercontent.com/fhIefT3XeJNU_3-gPWrNHJneLg6KrYCqF9Ps0uQecwwAUHHk3b62B0kvxo3z4o4c8arDTzodz6SxbYU=w1366-h635)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 635

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
... les menus sont comparés dans des langues différentes et comme ceux-ci sont différents d'une langue à l'autre, normal que l'erreur ressorte. Mais si on regarde langue par langue, les menus correspondent entre WP et Jahia.
