### ISSUE TITLE
Appel aux fichiers "externes" EPFL (utiliser HTTPS)

### ISSUE THREAD

**Issue by LuluTchab** [epfl-idevelop/jahiap#278]
Durant mes tests, j'ai rencontré un problème et je suis allé voir dans le fichier d'erreur Apache et je suis tombé sur ceci :

```
[Fri Oct 13 12:12:49.752604 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate v
erify failed in /srv/lchaboudez/localhost/htdocs/wp-content/themes/epfl/header.php on line 22
[Fri Oct 13 12:12:49.752703 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(): Failed to enable crypto in /srv/lchaboudez/localhost/htdocs/wp-content/themes/epfl/header.php on line 22
[Fri Oct 13 12:12:49.753653 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(http://www.epfl.ch/templates/fragments/header.sig.html): failed to open stream: operation failed in /srv/lchaboudez/localhost/htdocs/w
p-content/themes/epfl/header.php on line 22
[Fri Oct 13 12:12:50.382872 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate v
erify failed in /srv/lchaboudez/localhost/htdocs/wp-content/themes/epfl/header.php on line 32
[Fri Oct 13 12:12:50.382927 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(): Failed to enable crypto in /srv/lchaboudez/localhost/htdocs/wp-content/themes/epfl/header.php on line 32
[Fri Oct 13 12:12:50.383082 2017] [:error] [pid 55] [client 172.18.0.1:34482] PHP Warning:  readfile(http://www.epfl.ch/templates/fragments/header.fr.html): failed to open stream: operation failed in /srv/lchaboudez/localhost/htdocs/wp
-content/themes/epfl/header.php on line 32
```
Je suis allé jeter un coup d'oeil sur le fichier "header.php" et j'ai vu que les appels étaient fait en HTTP au lieu de HTTPS. La redirection est faite automatiquement par le serveur www.epfl.ch mais je pense que ça serait pas mal de directement faire les appels en HTTPS.

++

**Comment by LuluTchab** [comment]
Corrigé du côté de C2C et il n'y a plus d'erreur.
La redirection est faite correctement de HTTP vers HTTPS lors du "readfile" mais il serait bien de mettre "https" dans les liens.

**Comment by alinekeller** [comment]
Je ne comprends pas du tout de quels liens il est question…

**Comment by LuluTchab** [comment]
Ce ne sont pas des "liens" à proprement parler (sous entendu au sein d'une page web). Ce sont les fichiers que tu lis via la fonction `readfile` dans le fichier `header.php`.
Il y a 2 fichiers lu via `readfile` et c'est mis "http" au lieu de "https" dans l'URL. Y'a juste ça à changer.

**Comment by alinekeller** [comment]
Problème réglé avec le passage au header responsive :)

**Comment by LuluTchab** [comment]
@Escapevelocitycham : Ce problème concerne tous les sites donc il suffit de regarder sur un de ceux qui a été redéployé.

Ex:
http://test-web-wordpress.epfl.ch/v1-testwp/lanes
http://test-web-wordpress.epfl.ch/v1-testwp/events

**Comment by Escapevelocitycham** [comment]
Testé qq liens en random ... sans surprises, tous fonctionnent ...
Correction acceptée ...
