### ISSUE TITLE
SDF - Problèmes de formatages du corps de text.

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#93]
**Sender**: sdfepfl+sprey@gmail.com
**Comment**: Reprint n'est pas en rouge sur l'ancien site
[Open #25 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test-des-10x-sit-95b6215e/25)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/11-53/051191c2-7355-4754-a94b-fdcd2b328044.png'>![SDF - Problèmes de formatages du corps de text.](https://usersnappublic.s3.amazonaws.com/2017-07-17/11-53/f2894447-af7c-42dc-996f-368e539fec76.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/11-53/051191c2-7355-4754-a94b-fdcd2b328044.png'>Download original image</a>

**Browser**: Firefox 54 (Linux)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://ccc.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lcr.html](http://10.92.104.248:18081/toto?url1=http://ccc.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lcr.html)
**Screen size**: 2304 x 1440 **Browser size**: 2304 x 1314

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Fermeture de l'issue car la comparaison n'a pas été faite entre les 2 mêmes langues. Et check manuel effectué, enanglais ça a bien été mis en noir et en français en rouge. Donc pas d'erreur.
