### ISSUE TITLE
SDF - Barres de recherche google pas pareilles

### ISSUE THREAD

**Issue by czufferey** [epfl-idevelop/jahiap#98]
**Sender**: sdfepfl+urien@gmail.com
**Comment**: Barres de recherche google pas pareilles
[Open #71 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-h4bv/p/test-des-10x-sit-95b6215e/71)

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/12-37/920821f6-271c-48e0-a139-c3e1b9aba40e.png'>![SDF - Barres de recherche google pas pareilles](https://usersnappublic.s3.amazonaws.com/2017-07-17/12-37/1a3b9983-eb8b-445c-9912-217cc59f2556.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/12-37/920821f6-271c-48e0-a139-c3e1b9aba40e.png'>Download original image</a>

**Browser**: Firefox 54 (Windows 10)
**Referer**: [http://10.92.104.248:18081/toto?url1=http://lanes.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lanes.html](http://10.92.104.248:18081/toto?url1=http://lanes.epfl.ch&amp;url2=http://10.92.104.248:8081/test-web-wordpress.epfl.ch/v1-testwp/lanes.html)
**Screen size**: 2277 x 1280 **Browser size**: 2049 x 953

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by LuluTchab** [comment]
Boulot pour Aline?

**Comment by LuluTchab** [comment]
Redéployé sur http://test-web-wordpress.epfl.ch/v1-testwp/lanes

**Comment by Escapevelocitycham** [comment]
OK pour moi ...
